from __future__ import annotations

import re
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path

from unpack.engines.base import BaseEngine, DumpResult, EngineType
from unpack.utils.adb import get_device_serial

DEVICE_DUMP_DIR = "/data/local/tmp/unpack_ebpf"
DEVICE_SCRIPT_PATH = "/data/local/tmp/unpack_ebpf.bt"

_LIBART_PATHS = [
    "/apex/com.android.art/lib64/libart.so",
    "/apex/com.android.art/lib/libart.so",
    "/system/lib64/libart.so",
    "/system/lib/libart.so",
]

_SYMBOL_PATTERNS: dict[str, list[re.Pattern]] = {
    "dexfile_open": [
        re.compile(r"(_ZN3art\d*DexFileLoader\d*Open\w*)"),
        re.compile(r"(_ZN3art\d*DexFileLoader\d*OpenDexFile\w*)"),
        re.compile(r"(_ZN3art\d*OatFileAssistant\d*Open\w*)"),
    ],
    "dexfile_ctor": [
        re.compile(r"(_ZN3art7DexFileC[12]E\w*)"),
        re.compile(r"(_ZN3art7DexFileC[12]\w*)"),
    ],
    "define_class": [
        re.compile(r"(_ZN3art11ClassLinker11DefineClassE\w*)"),
        re.compile(r"(_ZN3art11ClassLinker11DefineClass\w*)"),
    ],
    "register_dexfile": [
        re.compile(r"(_ZN3art11ClassLinker15RegisterDexFileE\w*)"),
        re.compile(r"(_ZN3art11ClassLinker15RegisterDexFile\w*)"),
        re.compile(r"(_ZN3art11ClassLinker15RegisterDexFilesE\w*)"),
    ],
}


@dataclass
class _SymbolInfo:
    name: str
    offset: str
    probeable: bool = False


_BPFTRACE_TEMPLATE = r"""
#!/usr/bin/env bpftrace
// Auto-generated by unpack eBPF engine

BEGIN {{
    printf("EBPF_UNPACK: started\n");
    system("mkdir -p {dump_dir}");
}}

{probes}

END {{
    printf("EBPF_UNPACK: finished\n");
}}
"""

_UPROBE_DEXFILE_OPEN = r"""
uprobe:{libart}:{probe_target} {{
    printf("EBPF_UNPACK: dexfile_open pid=%d comm=%s\n", pid, comm);
}}
"""

_UPROBE_DEXFILE_CTOR = r"""
uprobe:{libart}:{probe_target} {{
    // DexFile::DexFile(const uint8_t* base, size_t size, ...)
    // AArch64 ABI: x0=this, x1=base, x2=size
    $base = reg("x1");
    $size = reg("x2");
    if ($size > 112 && $size < 104857600) {{
        $magic = *(uint32 *)$base;
        // 0x0a786564 == "dex\n" in little-endian
        if ($magic == 0x0a786564) {{
            $idx = @dex_count++;
            printf("EBPF_UNPACK: dex_dump base=0x%lx size=%lu idx=%d pid=%d\n",
                   $base, $size, $idx, pid);
            printf("EBPF_DUMP: %d 0x%lx %lu\n", pid, $base, $size);
        }}
    }}
}}
"""

_UPROBE_DEFINE_CLASS = r"""
uprobe:{libart}:{probe_target} {{
    printf("EBPF_UNPACK: define_class pid=%d comm=%s\n", pid, comm);
    @class_count++;
}}
"""

_UPROBE_REGISTER_DEXFILE = r"""
uprobe:{libart}:{probe_target} {{
    printf("EBPF_UNPACK: register_dexfile pid=%d comm=%s\n", pid, comm);
}}
"""

_DUMP_HELPER_SCRIPT = r"""#!/system/bin/sh
# Reads DEX from /proc/$1/mem at offset $2 with length $3, writes to $4
PID=$1
OFFSET=$2
LENGTH=$3
OUTFILE=$4

dd if=/proc/$PID/mem bs=1 skip=$((OFFSET)) count=$((LENGTH)) of="$OUTFILE" 2>/dev/null
if [ $? -eq 0 ] && [ -s "$OUTFILE" ]; then
    MAGIC=$(xxd -l 4 -p "$OUTFILE" 2>/dev/null)
    if [ "$MAGIC" = "6465780a" ]; then
        echo "OK: $OUTFILE ($LENGTH bytes)"
    else
        rm -f "$OUTFILE"
        echo "SKIP: bad magic at $OUTFILE"
    fi
else
    rm -f "$OUTFILE"
    echo "FAIL: could not read $OUTFILE"
fi
"""


def _push_file(serial: str, local_path: str, device_path: str):
    tmp_dest = f"/data/local/tmp/_unpack_push_{Path(device_path).name}"
    _adb(serial, "push", local_path, tmp_dest, timeout=30)
    _adb_shell(serial, f"mv {tmp_dest} {device_path}", root=True)


def _adb(serial: str, *args: str, timeout: int = 15) -> str:
    cmd = ["adb", "-s", serial, *args]
    return subprocess.check_output(cmd, text=True, timeout=timeout, stderr=subprocess.STDOUT).strip()


def _adb_shell(serial: str, cmd: str, timeout: int = 15, root: bool = False) -> str:
    if root:
        cmd = f"su -c '{cmd}'"
    return _adb(serial, "shell", cmd, timeout=timeout)


def _find_libart_path(serial: str) -> str | None:
    for path in _LIBART_PATHS:
        try:
            out = _adb_shell(serial, f"test -f {path} && echo exists", root=True)
            if "exists" in out:
                return path
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            continue
    return None


def _find_libart_symbols(serial: str) -> dict[str, _SymbolInfo]:
    libart = _find_libart_path(serial)
    if not libart:
        return {}

    try:
        out = _adb_shell(serial, f"readelf -sW {libart}", timeout=30, root=True)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        try:
            out = _adb_shell(serial, f"toybox readelf -sW {libart}", timeout=30, root=True)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            return {}

    symbols: dict[str, _SymbolInfo] = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 8:
            continue
        sym_name = parts[-1]
        try:
            sym_value = parts[1]
        except IndexError:
            sym_value = "0"
        for logical_name, patterns in _SYMBOL_PATTERNS.items():
            if logical_name in symbols:
                continue
            for pat in patterns:
                if pat.match(sym_name):
                    offset = f"0x{int(sym_value, 16):x}" if sym_value != "0" else "0x0"
                    symbols[logical_name] = _SymbolInfo(name=sym_name, offset=offset)
                    break

    return symbols


def _verify_symbols_probeable(
    serial: str, libart: str, symbols: dict[str, _SymbolInfo], bpftrace_bin: str,
) -> dict[str, _SymbolInfo]:
    for logical_name, info in symbols.items():
        try:
            out = _adb_shell(
                serial,
                f"{bpftrace_bin} -l 'uprobe:{libart}:{info.name}' 2>&1",
                root=True,
                timeout=10,
            )
            if "uprobe:" in out and "ERROR" not in out:
                info.probeable = True
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            pass

        if not info.probeable and info.offset != "0x0":
            try:
                out = _adb_shell(
                    serial,
                    f"{bpftrace_bin} -l 'uprobe:{libart}:{info.offset}' 2>&1",
                    root=True,
                    timeout=10,
                )
                if "uprobe:" in out and "ERROR" not in out:
                    info.probeable = True
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
                pass

    return symbols


def _check_root(serial: str) -> bool:
    try:
        out = _adb_shell(serial, "id", root=True)
        return "uid=0" in out
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return False


def _check_bpftrace(serial: str) -> bool:
    return _find_bpftrace_path(serial) is not None


def _find_bpftrace_path(serial: str) -> str | None:
    for candidate in ["/data/local/tmp/bpftrace", "/system/bin/bpftrace", "/sbin/bpftrace"]:
        try:
            out = _adb_shell(serial, f"test -x {candidate} && echo found", root=True)
            if "found" in out:
                return candidate
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            continue
    try:
        out = _adb_shell(serial, "which bpftrace 2>/dev/null", root=True)
        path = out.strip().splitlines()[0] if out.strip() else ""
        if path and "/" in path:
            return path
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        pass
    return None


def _check_kernel_ebpf(serial: str) -> bool:
    try:
        out = _adb_shell(serial, "uname -r", root=False)
        match = re.match(r"(\d+)\.(\d+)", out)
        if match:
            major, minor = int(match.group(1)), int(match.group(2))
            if (major, minor) >= (5, 4):
                return True
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        pass

    try:
        out = _adb_shell(serial, "zcat /proc/config.gz 2>/dev/null | grep CONFIG_BPF=", root=True)
        return "CONFIG_BPF=y" in out
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        pass

    return False


def _get_probe_target(info: _SymbolInfo) -> str:
    if info.probeable:
        return info.name
    if info.offset != "0x0":
        return info.offset
    return info.name


def _generate_bpftrace_script(
    libart: str, symbols: dict[str, _SymbolInfo],
) -> str:
    probes = []

    if "dexfile_open" in symbols:
        target = _get_probe_target(symbols["dexfile_open"])
        probes.append(
            _UPROBE_DEXFILE_OPEN.format(libart=libart, probe_target=target)
        )

    if "dexfile_ctor" in symbols:
        target = _get_probe_target(symbols["dexfile_ctor"])
        probes.append(
            _UPROBE_DEXFILE_CTOR.format(
                libart=libart, probe_target=target, dump_dir=DEVICE_DUMP_DIR,
            )
        )

    if "define_class" in symbols:
        target = _get_probe_target(symbols["define_class"])
        probes.append(
            _UPROBE_DEFINE_CLASS.format(libart=libart, probe_target=target)
        )

    if "register_dexfile" in symbols:
        target = _get_probe_target(symbols["register_dexfile"])
        probes.append(
            _UPROBE_REGISTER_DEXFILE.format(libart=libart, probe_target=target)
        )

    return _BPFTRACE_TEMPLATE.format(
        dump_dir=DEVICE_DUMP_DIR,
        probes="\n".join(probes),
    )


class EbpfEngine(BaseEngine):
    engine_type = EngineType.EBPF

    def __init__(self, wait_seconds: int = 20):
        self._wait_seconds = wait_seconds
        self._serial: str | None = None
        self._unavailable_reason: str | None = None

    def is_available(self) -> bool:
        serial = get_device_serial()
        if not serial:
            self._unavailable_reason = "no ADB device connected"
            return False
        self._serial = serial

        if not _check_root(serial):
            self._unavailable_reason = (
                "device is not rooted -- eBPF engine requires root "
                "(adb shell su -c id must return uid=0)"
            )
            return False

        if not _check_kernel_ebpf(serial):
            self._unavailable_reason = (
                "kernel does not support eBPF -- requires kernel >= 5.4 "
                "with CONFIG_BPF=y"
            )
            return False

        if not _check_bpftrace(serial):
            self._unavailable_reason = (
                "bpftrace not found on device -- push a static bpftrace binary "
                "to /data/local/tmp/bpftrace"
            )
            return False

        return True

    @property
    def unavailable_reason(self) -> str | None:
        return self._unavailable_reason

    def dump(
        self,
        package_name: str,
        output_dir: Path,
        device_serial: str | None = None,
    ) -> DumpResult:
        result = DumpResult(engine=self.engine_type)
        t0 = time.monotonic_ns()
        serial = device_serial or self._serial or get_device_serial()

        if not serial:
            result.error = "no ADB device connected"
            result.duration_ms = int((time.monotonic_ns() - t0) / 1_000_000)
            return result

        try:
            result = self._do_dump(serial, package_name, output_dir, result)
        except Exception as exc:
            result.error = str(exc)
        finally:
            self._cleanup(serial)
            result.duration_ms = int((time.monotonic_ns() - t0) / 1_000_000)

        return result

    def _do_dump(
        self,
        serial: str,
        package_name: str,
        output_dir: Path,
        result: DumpResult,
    ) -> DumpResult:
        libart = _find_libart_path(serial)
        if not libart:
            result.error = "libart.so not found on device"
            return result

        bpftrace_bin = _find_bpftrace_path(serial)
        if not bpftrace_bin:
            result.error = "bpftrace not found on device"
            return result

        symbols = _find_libart_symbols(serial)
        if not symbols:
            result.error = (
                "no usable libart.so symbols found -- "
                "readelf may be missing or libart.so is stripped"
            )
            return result

        symbols = _verify_symbols_probeable(serial, libart, symbols, bpftrace_bin)

        usable = [
            k for k in ("dexfile_ctor", "dexfile_open", "register_dexfile")
            if k in symbols and (symbols[k].probeable or symbols[k].offset != "0x0")
        ]
        if not usable:
            not_probeable = {
                k: {"name": v.name, "offset": v.offset}
                for k, v in symbols.items()
            }
            result.error = (
                f"no probeable symbols found. Symbols detected but not traceable: "
                f"{not_probeable}. Try pushing a newer bpftrace or check "
                f"/sys/kernel/tracing/available_filter_functions."
            )
            return result

        script_content = _generate_bpftrace_script(libart, symbols)

        _adb_shell(serial, f"mkdir -p {DEVICE_DUMP_DIR} && chmod 777 {DEVICE_DUMP_DIR}", root=True)

        with tempfile.NamedTemporaryFile(mode="w", suffix=".bt", delete=False) as f:
            f.write(script_content)
            local_script = f.name

        try:
            _push_file(serial, local_script, DEVICE_SCRIPT_PATH)
        finally:
            Path(local_script).unlink(missing_ok=True)

        _adb_shell(serial, f"chmod 755 {DEVICE_SCRIPT_PATH}", root=True)

        device_helper = f"{DEVICE_DUMP_DIR}/dump_helper.sh"
        with tempfile.NamedTemporaryFile(mode="w", suffix=".sh", delete=False) as f:
            f.write(_DUMP_HELPER_SCRIPT)
            local_helper = f.name
        try:
            _push_file(serial, local_helper, device_helper)
        finally:
            Path(local_helper).unlink(missing_ok=True)
        _adb_shell(serial, f"chmod 755 {device_helper}", root=True)

        bpftrace_cmd = (
            f"nohup {bpftrace_bin} {DEVICE_SCRIPT_PATH} "
            f"> {DEVICE_DUMP_DIR}/bpftrace.log 2>&1 &"
        )
        _adb_shell(serial, bpftrace_cmd, root=True)

        # Wait for bpftrace to compile BPF programs and attach probes
        attached = False
        for _ in range(8):
            time.sleep(1)
            try:
                log = _adb_shell(
                    serial,
                    f"cat {DEVICE_DUMP_DIR}/bpftrace.log 2>/dev/null || true",
                    root=True, timeout=5,
                )
                if "Attaching" in log or "EBPF_UNPACK: started" in log:
                    attached = True
                    break
                if "ERROR" in log:
                    result.error = f"bpftrace failed: {log.strip()[:500]}"
                    return result
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
                pass

            try:
                ps_out = _adb_shell(serial, f"pgrep -f {bpftrace_bin} || true", root=True)
                if not ps_out.strip():
                    log = _adb_shell(
                        serial,
                        f"cat {DEVICE_DUMP_DIR}/bpftrace.log 2>/dev/null || true",
                        root=True, timeout=5,
                    )
                    result.error = f"bpftrace exited prematurely. Log: {log.strip()[:500]}"
                    return result
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
                pass

        if not attached:
            try:
                log = _adb_shell(
                    serial,
                    f"cat {DEVICE_DUMP_DIR}/bpftrace.log 2>/dev/null || true",
                    root=True, timeout=5,
                )
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
                log = "(could not read log)"
            result.error = (
                f"bpftrace did not confirm attachment after 8s. "
                f"Log: {log.strip()[:500]}"
            )
            return result

        try:
            _adb_shell(serial, f"am force-stop {package_name}", root=False, timeout=5)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            pass
        time.sleep(0.5)

        try:
            _adb_shell(
                serial,
                f"monkey -p {package_name} -c android.intent.category.LAUNCHER 1",
                root=False,
                timeout=10,
            )
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            result.error = f"failed to launch {package_name}"
            return result

        time.sleep(self._wait_seconds)

        try:
            log = _adb_shell(
                serial,
                f"cat {DEVICE_DUMP_DIR}/bpftrace.log 2>/dev/null || true",
                root=True,
                timeout=10,
            )
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            log = ""

        dump_entries = _parse_dump_entries(log)

        for i, (pid, base_addr, size) in enumerate(dump_entries):
            dex_device_path = f"{DEVICE_DUMP_DIR}/dex_{i:03d}.dex"
            try:
                _adb_shell(
                    serial,
                    f"sh {device_helper} {pid} {base_addr} {size} {dex_device_path}",
                    root=True,
                    timeout=30,
                )
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
                continue

        try:
            ls_out = _adb_shell(serial, f"ls {DEVICE_DUMP_DIR}/*.dex 2>/dev/null || true", root=True)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            ls_out = ""

        output_dir.mkdir(parents=True, exist_ok=True)
        for line in ls_out.splitlines():
            device_path = line.strip()
            if not device_path.endswith(".dex"):
                continue
            local_name = Path(device_path).name
            local_path = output_dir / f"ebpf_{local_name}"
            try:
                _adb(serial, "pull", device_path, str(local_path), timeout=30)
                if local_path.stat().st_size > 112:
                    result.dex_files.append(local_path)
                else:
                    local_path.unlink(missing_ok=True)
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
                continue

        result.success = len(result.dex_files) > 0
        if not result.success and not result.error:
            probe_details = {
                k: {"target": _get_probe_target(v), "verified": v.probeable}
                for k, v in symbols.items() if k in usable
            }
            result.error = (
                f"no DEX files captured. "
                f"Probes used: {probe_details}. "
                f"Check {DEVICE_DUMP_DIR}/bpftrace.log on device."
            )

        return result

    def _cleanup(self, serial: str):
        bpftrace_bin = _find_bpftrace_path(serial)
        kill_patterns = ["bpftrace"]
        if bpftrace_bin:
            kill_patterns.append(bpftrace_bin)
        for pat in kill_patterns:
            try:
                _adb_shell(serial, f"pkill -f '{pat}' || true", root=True, timeout=5)
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
                pass
        try:
            _adb_shell(serial, f"rm -f {DEVICE_SCRIPT_PATH}", root=True, timeout=5)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            pass


def _parse_dump_entries(log: str) -> list[tuple[int, int, int]]:
    entries = []
    for line in log.splitlines():
        line = line.strip()
        if not line.startswith("EBPF_DUMP:"):
            continue
        parts = line.split()
        if len(parts) < 4:
            continue
        try:
            pid = int(parts[1])
            base_addr = int(parts[2], 16)
            size = int(parts[3])
            if size > 112 and size < 100 * 1024 * 1024:
                entries.append((pid, base_addr, size))
        except (ValueError, IndexError):
            continue
    return entries
